### ISSUE TITLE
Doesn't work with Blender v2.79

### ISSUE THREAD

**Issue by Sunchock** [alrusdi/blender-b3d-exporter#1]
Hello, b3d_exporter.py doesn't work on blender 2.79. When I try to run script, i get an error :

> File "/b3d_export.py", line 713
       mesh_stack[vert.index][4][0].append([face.index, vert.uvco[0]])
TabError: Inconsistent use of tags and spaces in indentation

**Comment by alrusdi** [comment]
Oh. This is not mine project. Very old and unsupported. But I believe it should work with Blender: 248a
